$bat = Join-Path $PSScriptRoot "BuildAndRun.bat"
$lines = @(
    '@chcp 65001 > nul',
    '@echo off',
    'setlocal EnableDelayedExpansion',
    '',
    ':: -- Configuration ----------------------------------------------------------',
    'set "ACCORE_EXE=C:\Program Files\Autodesk\AutoCAD 2023\accoreconsole.exe"',
    'set "ROOT=%~dp0"',
    'set "PROJECT=%ROOT%CadParsing\CadParsing.csproj"',
    'set "DLL=%ROOT%CadParsing\bin\Debug\net48\CadParsing.dll"',
    'set "SCRIPT=%ROOT%RunProgram.scr"',
    '',
    ':: -- [1/2] Build ------------------------------------------------------------',
    'echo [1/2] Building CadParsing (net48 x64 Debug)...',
    'dotnet build "%PROJECT%" -c Debug',
    'if %ERRORLEVEL% NEQ 0 (',
    '    echo.',
    '    echo BUILD FAILED. Aborting.',
    '    exit /b 1',
    ')',
    '',
    ':: -- [2/2] Generate RunProgram.scr ------------------------------------------',
    'echo [2/2] Writing RunProgram.scr...',
    'powershell -NoProfile -Command "Set-Content -Path ''%SCRIPT%'' -Value ''NETLOAD'', ''%DLL%'', ''LISTXREFLAYERS'', ''BINDXREF'', ''EXPLODEBLOCK'', ''DETECTBORDER'', ''EXPORTPDF'' -Encoding ASCII"',
    '',
    ':: -- Process each DWG path from dwg_path.txt --------------------------------',
    'for /f "usebackq delims=" %%a in ("%ROOT%dwg_path.txt") do (',
    '    if not exist "%%a" (',
    '        echo.',
    '        echo [WARN] DWG file not found, skipping:',
    '        echo   %%a',
    '    ) else (',
    '        echo.',
    '        echo [OK] DWG file found: %%a',
    '        echo Running accoreconsole.exe...',
    '        "%ACCORE_EXE%" /i "%%a" /s "%SCRIPT%" /l "ko-KR"',
    '    )',
    ')',
    '',
    'endlocal'
)
[System.IO.File]::WriteAllLines($bat, $lines, [System.Text.Encoding]::ASCII)
Write-Host "BuildAndRun.bat written: $((Get-Item $bat).Length) bytes"
